site_name: Damon Henry
site_url: https://romanumero.github.io
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
  palette:
    scheme: default
    #primary: white
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/romanumero
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/damonhenry/
copyright: Copyright &copy; 2025 Damon Henry
nav:
  - Home:
      - Introductions: "index.md"
      #- User Manual: "user_manual.md"
      - Books: "books.md"
      - Tools: "tools.md"
      - Companies: "companies.md"
  - Thoughts and Rambles:
      - thoughts/index.md
plugins:
  - blog:
      include_in_nav: false
      blog_dir: thoughts
      blog_toc: true
  - search
extra_css:
  - ./css/global.css
markdown_extensions:
  - toc:
      permalink: true
