site_name: Damon Henry
site_url: https://romanumero.github.io
nav:
  - Home:
      - Archive:
          - 2025: archive/2024.md
      - Categories:
          - Democratizing marketing: categories/applied-ai.md
          #- Consulting: categories/consulting.md
          - Losing my Hands: categories/losing-my-hands.md
          - Personal: categories/personal.md
          - Personal Growth: categories/personal-growth.md
          - Leadership: categories/rag.md
          - Software Engineering: categories/software-engineering.md
          - Thoughts: categories/thoughts.md
theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.sections
  palette:
    scheme: slate
    primary: white
    extra:
social:
  - icon: fontawesome/brands/x-twitter
    link: https://twitter.com/romanumero
copyright: Copyright &copy; 2025 Damon Henry
