site_name: Damon Henry
site_url: https://romanumero.github.io
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
  icons:
    search: material/magnify
  palette:
    scheme: default
    #primary: white
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/romanumero
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/damonhenry/
copyright: Copyright &copy; 2025 Damon Henry
nav:
  - Home:
      - Introductions: "index.md"
      #- User Manual: "user_manual.md"
      - Books: "books.md"
      - Tools: "tools.md"
      - Companies: "companies.md"
  - Thoughts and Ramblings:
      - thoughts/index.md
plugins:
  - blog:
      include_in_nav: false
      blog_dir: thoughts
      blog_toc: true
      post_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
  - search
extra_css:
  - ./css/global.css
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
