site_name: Damon Henry
site_url: https://romanumero.github.io
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
  palette:
    scheme: slate
    primary: white
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/romanumero
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/damonhenry/
copyright: Copyright &copy; 2025 Damon Henry
nav:
  - index.md
  - Thoughts and Rambles:
      - writing/index.md
plugins:
  - blog:
      include_in_nav: false
      blog_dir: writing
      blog_toc: true
  - search
